repo_url: https://github.com/uiuc-kang-lab/agentic-benchmarks
repo_name: uiuc-kang-lab/agentic-benchmarks
site_name: "Agentic Benchmark Checklist"
theme:
  name: material
  custom_dir: material/overrides
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  # palette:
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/link
  #       name: Switch to light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: black
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off
  #       name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  # icon:
  #   logo: logo
extra_css:
  - styles/extra.css
nav:
  - Home: index.md
  - Checklist: assets/checklist.pdf
  # - Findings: findings.md
  - Contribute: contribute.md
plugins:
  - table-reader
  - search:
      enabled: false
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
